version: '1.0.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./EbayChromeApp.sln --verbosity m
build_script:
  - cmd: dotnet publish -c Release -o ../out ./\EbayChromeApp.Backend/EbayChromeApp.Backend.csproj
test: off
artifacts:
- path: ./out
  name: ebay-extension
  type: WebDeployPackage
deploy:
- provider: AzureAppServiceZipDeploy
  appservice_environment: true
  website: rebaysearch
  username: $rebaysearch
  password:
    secure: W5R6ZKzp5+JvxT4W0beiraoXKrgZSo5+iGFJy9/09ymY686oZBG9i9Wgk1/Sg3fkKVt0bsTWbkzhFsCvinSIFQ==
  artifact: ebay-extension.zip
  appservice_environment_name: rebaysearch