version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
environment:
  nodejs_version: "8.9.3"
init:
  # Good practise, because Windows line endings are different from 
Unix/Linux ones
  - cmd: git config --global core.autocrlf true
install:
  # Install repo specific stuff here
  - ps: Install-Product node $env:nodejs_version
  - npm install -g npm
  - npm install
before_build:
  - cmd: node --version
  - cmd: npm --version
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./EbayChromeApp.sln --verbosity m
build_script:
  - cmd: 
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish -c Release -o ../out ./\EbayChromeApp.Backend/EbayChromeApp.Backend.csproj
after_build:
  # For once the build has completed
artifacts:
 - path: '\out'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
    #test_script:
    # restore packages for our unit tests
    #- cmd: dotnet restore ./src/BookTracker.Web.Test/BookTracker.Web.Test.csproj --verbosity m
    # run the unit tests (requires changing into the test directory)
    #- cmd: cd src/BookTracker.Web.Test
    #- cmd: dotnet xunit
  
    # restore packages for our unit tests
    #- cmd: dotnet restore ./src/BookTracker.Services.Test/BookTracker.Services.Test.csproj --verbosity m
    # run the unit tests (requires changing into the test directory)
    #- cmd: cd src/BookTracker.Services.Test
    #- cmd: dotnet xunit
on_finish :
  # any cleanup in here
deploy: off
