version: '1.0.{build}'
image: Visual Studio 2017
configuration: Release
platform: Any CPU
clone_depth: 1
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./EbayChromeApp.sln --verbosity m
build_script:
  - cmd: dotnet publish -c Release -o ../out ./\EbayChromeApp.Backend/EbayChromeApp.Backend.csproj
test: off
artifacts:
- path: ./out
  name: ebay-extension
  type: WebDeployPackage
deploy: off
