version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
environment:
  nodejs_version: "8.9.3"
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./EbayChromeApp.sln --verbosity m
build_script:
  - cmd: dotnet publish -c Release -o ../out ./\EbayChromeApp.Backend/EbayChromeApp.Backend.csproj
artifacts:
  - path: '\out'
   name: WebSite
   type: WebDeployPackage
clone_depth: 1
on_finish :
  # any cleanup in here
deploy: off
