export const API_REQUEST_BEGIN = 'API_REQUEST_BEGIN'
export const API_REQUEST_END = 'API_REQUEST_END'
export const API_REQUEST_ERROR = 'API_REQUEST_ERROR'
export const API_REQUEST_LOG = 'API_REQUEST_LOG'

export const SEARCH_SLUG = 'SEARCH_SLUG'
export const RETRIVED_SLUG = 'RETRIVED_SLUG'

export const SEARCH_DETAILED_ASSET = 'SEARCH_DETAILED_ASSET'
export const RETRIVED_DETAILED_ASSET = 'RETRIVED_DETAILED_ASSET'


export const FETCH_DETAIL = 'FETCH_DETAIL'
export const FETCHING_DETAIL = 'FETCHING_DETAIL'
export const FETCHED_DETAIL = 'FETCHED_DETAIL'
export const NOT_FETCHED_DETAIL = 'NOT_FETCHED_DETAIL'

export const CLEAR_DATA = 'CLEAR_DATA'

export const FETCHING_KEYWORD = 'FETCHING_KEYWORD'
export const FETCHED_KEYWORD = 'FETCHED_KEYWORD'
export const FETHING_PRODUCTIES = 'FETHING_PRODUCTIES'
export const FETCHED_PRODUCTIES = 'FETCHED_PRODUCTIES'