// <auto-generated />
using EbayChromeApp.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EbayChromeApp.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20180506235757_InitialDb")]
    partial class InitialDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("EbayChromeApp.Backend.Models.Search", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("IP");

                    b.Property<string>("Query");

                    b.HasKey("Id");

                    b.HasIndex("Created");

                    b.HasIndex("IP");

                    b.ToTable("Search");
                });
#pragma warning restore 612, 618
        }
    }
}
